name: Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'zinit*.zsh'
  push:
    branches:
      - main
    paths:
      - 'zinit*.zsh'
  workflow_dispatch:

jobs:
  zshelldoc:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: re-generate documentation
        run: |
          make doc/container
          sudo chown -R "$(id -u):$(id -g)" .

      - name: commit and push updated docs
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'doc'
          author_name: GitHub Actions
          author_email: actions@github.com
          commit: --signoff
          message: 'docs: generate'
          push: true
